version: "3"

vars:
    VENV: .venv

tasks:
    virtualenv:
        summary: Create a Python 3 virtualenv
        cmds:
          - "python3 -m venv {{.VENV}}"
          - "source {{.VENV}}/bin/activate"
          - "{{.VENV}}/bin/pip install --upgrade pip"
          - "{{.VENV}}/bin/pip install -r requirements.txt"
        sources:
          - requirements.txt
        method: checksum